remote_theme: just-the-docs/just-the-docs
title: Umbrel Apps
description: UmbrelApps Store
author: Dax Sosa
url: "https://umbrelapps.daxsosa.com"
baseurl: ""

# Navigation
aux_links:
  "View on GitHub":
    - "//github.com/TheBitcoinBackup/Self-Inheritance-Protocol"
aux_links_new_tab: true

# Footer content
footer_content: "Created by Dax Sosa·"
