version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sphinx-relay_server_1
      APP_PORT: $APP_SPHINX_RELAY_PORT
      PROXY_AUTH_ADD: "false"

  server:
    image: sphinxlightning/sphinx-relay:v2.3.1@sha256:19dd49476fb7a38a8123a2cbfcfe5dc5c1cb1ad69ac0904e9b24657f2943aba3
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/relay/.lnd/
    environment:
      PUBLIC_URL: "$APP_HIDDEN_SERVICE:$APP_SPHINX_RELAY_PORT"
      LND_IP: $APP_LIGHTNING_NODE_IP
      CONNECT_UI: "true"
      LND_PORT: $APP_LIGHTNING_NODE_GRPC_PORT
      TLS_LOCATION: /lnd/tls.cert
      MACAROON_LOCATION: /lnd/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/admin.macaroon
      LND_LOG_LOCATION: /lnd/logs/bitcoin/${APP_BITCOIN_NETWORK}/lnd.log
