version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ord_ord_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  ord:
    # add mult-arch sha256 when available
    image: nmfretz/ord:v0.5.1
    # user: "1000:1000"
    restart: on-failure
    command: "--first-inscription-height 770112 --data-dir /var/lib/ord --bitcoin-data-dir /var/lib/bitcoind --rpc-url ${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT} --chain ${APP_BITCOIN_NETWORK} server --http"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/ord
      - ${APP_BITCOIN_DATA_DIR}:/var/lib/bitcoind:ro