version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: specter-desktop_web_1
      APP_PORT: 25441

  web:
    image: lncm/specter-desktop:v2.0.1@sha256:824999af780b354bb4e2e649c08d95c03aaf2dd2918a6172f0ed2d6688bfd7b1
    stop_signal: SIGINT
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --host=0.0.0.0
      - --specter-data-folder=/data
    environment:
      # TODO: APP_PASSWORD
      BTC_RPC_USER: $APP_BITCOIN_RPC_USER
      BTC_RPC_PASSWORD: $APP_BITCOIN_RPC_PASS
      BTC_RPC_HOST: $APP_BITCOIN_NODE_IP
      BTC_RPC_PORT: $APP_BITCOIN_RPC_PORT
      BTC_RPC_PROTOCOL: http
